worgarside/home-assistant

- includes/template/templates.yaml
- pyscript/scripts/yas_209/triggered_functions.py
- Add sensor for YAS-209 Local IP
- Consume sensor in Pyscript module
> Add sensor for YAS-209 Local IP

- .github/workflows/delete_pr_branch.yml
- pyproject.toml
- Release 0.3.0 (#184)
- Bump to 0.4.0
> Merge `release/0.4.0` back into `develop`

- includes/template/templates.yaml
- pyproject.toml
Co-authored-by: Will Garside <worgarside@gmail.com>
> Release 0.6.1

- includes/automation/devices.yaml
- includes/template/templates.yaml
- lovelace/views/mobile_dashboard.yaml
- Add `binary_sensor.will_s_macbook_pro_docked`
- Include new sensor in automations
- Add new sensor to lovelace
> Add `binary_sensor.will_s_macbook_pro_docked`

- .github/workflows/create_new_release.yml
- Add GHA to create new release branch
- Fix workflow path
> Add GHA to create new release branch

- .pre-commit-config.yaml
- entities/shell_command/comment_on_pr.yaml
- integrations/lovelace.yaml
- lovelace/decluttering_templates.yaml
- pyproject.toml
- resources/shell_command/gh_cli/comment_on_pr.sh
- [pre-commit.ci] pre-commit autoupdate (#378)
- Add dependabot command shortcuts to GitHub dashboard (#380)
- Bump version to 1.4.0
> Release 1.4.0

- .pre-commit-config.yaml
- dev_tools/add_webhook_to_repo/add_webhook_to_repo.fish
- entities/automation/webhook/update_pull_request_sensor.yaml
- entities/command_line/sensor/github_pull_requests/addon_rss_log_feed_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/addon_yas_209_bridge_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/github_config_files_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/home_assistant_config_validator_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/home_assistant_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/led_matrix_now_playing_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/plant_monitor_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/python_template_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/smart_mini_crt_interface_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/useful_devops_scripts_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/very_slow_movie_player_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/wg_scripts_pull_requests.yaml
- entities/command_line/sensor/github_pull_requests/wg_utilities_pull_requests.yaml
- Reduce PR sensor update frequency to hourly
- Add webhook trigger for PR sensors
> Add webhook trigger for PR sensors

- entities/automation/remote/office_speakers/single_press.yaml
Includes a refactor of the automation logic
> Play music when turning Office Speakers on

- .github/workflows/create_new_release.yml
- entities/automation/cover/bedroom_blinds/close_after_sunset.yaml
- entities/automation/cover/lounge_blinds/close_after_sunset.yaml
- entities/automation/cover/office_blinds/close_after_sunset.yaml
- Update blinds to close at -3'
- Unrelated: fix for GHA perms
> Unrelated: fix for GHA perms

- .pre-commit-config.yaml
- .pylintrc
- integrations/logger.yaml
- poetry.lock
- pyproject.toml
- pyscript/modules/helpers.py
- pyscript/requirements.txt
- pyscript/scripts/google_fit/variables.py
- pyscript/scripts/monzo/services.py
- pyscript/scripts/truelayer/variables.py
- 4afd875 | Update `wg-utilities`
- 37a9ebe | Update HAExceptionCatcher to use ItemWH
- a3a6156 | Update existing logs
- fccde84 | Fix test typo
> Update HAExceptionCatcher to use ItemWH

- entities/input_number/lounge_blinds_button_height.yaml
- entities/input_number/office_desk_sitting_height.yaml
- entities/input_number/office_desk_standing_height.yaml
- entities/input_number/office_desk_standing_mode_percentage_target.yaml
- entities/input_number/st_macbook_pro_full_battery_threshold.yaml
- entities/input_number/st_macbook_pro_low_battery_threshold.yaml
- entities/input_number/will_s_macbook_pro_full_battery_threshold.yaml
- entities/input_number/will_s_macbook_pro_low_battery_threshold.yaml
- aa2993a | Remove unnecessary initial values for input numbers
> Remove unnecessary initial values for input numbers

- .pre-commit-config.yaml
- 8c3420d | Add PCH dep synchroniser
> Add PCH dep synchroniser

- entities/automation/switch/st_macbook_pro/turn_off_when_battery_full.yaml
- entities/automation/switch/st_macbook_pro/turn_off_when_undocked.yaml
- entities/automation/switch/st_macbook_pro/turn_on_when_battery_low.yaml
- entities/automation/switch/st_macbook_pro/turn_on_when_docked.yaml
- entities/automation/switch/will_s_macbook_pro/turn_off_when_battery_full.yaml
- entities/automation/switch/will_s_macbook_pro/turn_off_when_undocked.yaml
- entities/automation/switch/will_s_macbook_pro/turn_on_when_battery_low.yaml
- entities/automation/switch/will_s_macbook_pro/turn_on_when_docked.yaml
- entities/template/binary_sensor/st_macbook_pro_docked.yaml
- entities/template/binary_sensor/will_s_macbook_pro_docked.yaml
- lovelace/views/mobile_dashboard.yaml
- Update automations for single MBP charger
- Fix monitor count for dock binary sensors
- Update dashboard control
> Update dashboard control

- entities/automation/remote/lounge_desk/double_press.yaml
- entities/automation/remote/lounge_desk/single_press.yaml
- 5db1c87 | Add extra functionality to lounge desk button
- a9b6f3a | Update to turn all lounge lights on
> Add extra functionality to lounge desk button

- lovelace/views/mobile_dashboard.yaml
- 3668498 | Add mini lamp to dashboard
> Add mini lamp to dashboard

- entities/automation/webhook/get_latest_release.yaml
- entities/command_line/sensor/current_git_branch.yaml
- entities/command_line/sensor/current_git_ref.yaml
- entities/shell_command/checkout_develop_head.yaml
- entities/shell_command/get_latest_release.yaml
- resources/shell_command/git/get_latest_release.sh
- 9ed957e | Add webhook to get latest release
- d10b88e | Fix bad file path
- ae55513 | Add payload validation and notification
- bdab50c | Add sensors for current git ref/branch
> Add webhook to get latest release/git command updates

- .gitignore
- integrations/frontend.yaml
- 9bb4a58 | Enable HACS themes
- e7aa25b | Fix path
- ac09460 | Add themes to .gitignore
> Enable HACS themes

- entities/automation/webhook/get_latest_release.yaml
- 5f70ac2 | Update Git sensors after `git pull`ing latest reelase
> Update Git sensors after `git pull`ing latest reelase

- entities/binary_sensor/clmtpi_online.yaml
- entities/binary_sensor/crtpi_online.yaml
- entities/binary_sensor/growpi_online.yaml
- entities/binary_sensor/mtrxpi_online.yaml
- entities/binary_sensor/rtropi_online.yaml
- entities/binary_sensor/vsmppi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/clmtpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/crtpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/growpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/mtrxpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/rtropi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/vsmppi_online.yaml
- da89f06 | Update Pi-Online sensors to be time-since-last-updated based
- 785169e | Fix typos ;_;
- d47c768 | Update device classes
> Update Pi-Online sensors to be time-since-last-updated based

- integrations/lovelace.yaml
- b1cc90d | Update swipe navigation for lovelace
> Update swipe navigation for lovelace

- .gitignore
- entities/var/truelayer/truelayer_balance_starling_current_account.yaml
- entities/var/truelayer/truelayer_balance_starling_joint_account.yaml
- secrets.fake.yaml
- c3515d7 | Add Starling account variables
- d7147ed | Update fake secrets
- 3fc115f | Bump `worgarside/home-assistant-appdaemon` to 0.3.0
> Add Starling account variables & AppDaemon apps

- lovelace/views/system_health.yaml
- 8d11e8f | Fix typo on Lovelace action
> Fix typo on Lovelace action

- entities/automation/webhook/get_latest_release.yaml
- entities/command_line/sensor/current_appdaemon_branch.yaml
- entities/command_line/sensor/current_appdaemon_ref.yaml
- 12aebe5 | Add git sensors for AppDaemon submodule
> Add git sensors for AppDaemon submodule

- entities/automation/switch/office_amp/auto_turn_off.yaml
- 0745f47 | Update `switch.office_amp` auto-turn off triggers
> Update `switch.office_amp` auto-turn off triggers

- entities/automation/cover/bedroom_blinds/register_stop_state.yaml
- entities/automation/cover/lounge_blinds/register_stop_state.yaml
- entities/automation/cover/office_blinds/register_stop_state.yaml
- 225e38c | Stop blinds hanging in `opening`/`closing` state when opened <100%
> Stop blinds hanging in `opening`/`closing` state when opened <100%

- entities/device_tracker/google_maps/google_maps_location_tracker_email.yaml
- secrets.fake.yaml
- f400efd | Remove secondary Google Maps account
- da6db10 | Remove fake secret
> Remove secondary Google Maps account

- entities/var/google_fit/google_fit_active_minutes.yaml
- entities/var/google_fit/google_fit_calories_expended.yaml
- entities/var/google_fit/google_fit_distance_moved.yaml
- entities/var/google_fit/google_fit_step_count.yaml
- entities/var/google_fit/google_fit_weight.yaml
- secrets.fake.yaml
- 4b8a737 | Deprecate custom Google Fit variables
> Deprecate custom Google Fit variables

- entities/template/sensor/entity_counts/count_stale_entities.yaml
- lovelace/views/system_health.yaml
- 15ad5b5 | Add stale entities sensor
- a177030 | Fix JSON serializing issue
> Add stale entities sensor

- .github/labeler.yml
- integrations/lovelace.yaml
- 15c3035 | Add Expander Card
- 302e76d | Update labeler config
- 2818e0f | Update labeler config
> Add Expander Card

- config_validator.json
- entities/var/auto_save_amount.yaml
- entities/var/spotify/spotify_tempo_will.yaml
- entities/var/tasker/tasker_pixel_now_playing.yaml
- entities/var/truelayer/truelayer_balance_amex.yaml
- entities/var/truelayer/truelayer_balance_hsbc_current_account.yaml
- entities/var/truelayer/truelayer_balance_monzo_credit_cards.yaml
- entities/var/truelayer/truelayer_balance_monzo_current_account.yaml
- entities/var/truelayer/truelayer_balance_monzo_savings.yaml
- entities/var/truelayer/truelayer_balance_santander_current_account.yaml
- entities/var/truelayer/truelayer_balance_santander_savings_account.yaml
- entities/var/truelayer/truelayer_balance_starling_current_account.yaml
- entities/var/truelayer/truelayer_balance_starling_joint_account.yaml
- 0d8634f | Update `var` config to validate `unique_id`
> Update `var` config to validate `unique_id`

- entities/automation/person/vic/toggle_adguard.yaml
- b0dd640 | Fix bad condition in AdGuard toggle automation
> Fix bad condition in AdGuard toggle automation

- entities/automation/tag/cosmo/bedroom.yaml
- entities/automation/tag/cosmo/en_suite.yaml
- entities/automation/tag/cosmo/hallway.yaml
- entities/automation/tag/cosmo/kitchen.yaml
- entities/automation/tag/cosmo/lounge.yaml
- entities/automation/tag/cosmo/office.yaml
- entities/automation/tag/cosmo/return_to_base.yaml
- entities/script/cosmo/cosmo_tag_scanned.yaml
- 1cd7e20 | Add automations and script for Cosmo's NFC tags
- 1225fce | Fix syntax
- e4d4c0c | Fix more syntax
- 96dfa8b | More syntax fixes ;_;
- 3e0a488 | Even more syntax fixes (fml)
- a479198 | Fix kitchen media player
- bb29b95 | Fix kitchen name
- 4a08e70 | Add tag for returning to base
- 4661455 | Add missing variable definition
- ee95e9c | Stop Cosmo before re-assigning
> Add NFC tag automations for Cosmo!

- entities/template/binary_sensor/vic_at_work.yaml
- df7236a | Add `binary_sensor.vic_at_work`
> Add `binary_sensor.vic_at_work`

- entities/template/binary_sensor/vic_at_work.yaml
- f833df6 | Fix syntax typo in template sensor
> Fix syntax typo in template sensor

- entities/script/cosmo/cosmo_get_room_id_or_name.yaml
- entities/template/binary_sensor/vic_at_work.yaml
- f833df6 | Fix syntax typo in template sensor
- 786e4ad | Remove bad "type" value in script config
- bc4c1f7 | Remove `error: false` option
> Remove `error: false` option

- entities/automation/binary_sensor/front_door/open.yaml
- entities/automation/binary_sensor/hallway_motion_sensor/off_for_5_minutes.yaml
- entities/automation/binary_sensor/hallway_motion_sensor/on.yaml
- 1159251 | Automate hallway lights when front door opened
- 4b79931 | Add motion-based automations for hallway lights
> Automate hallway lights

- entities/automation/binary_sensor/front_door/open.yaml
- entities/automation/binary_sensor/hallway_motion_sensor/on.yaml
- 6140964 | Add conditions to the hallway light automations to reduce conflicts etc.
> Add conditions to the hallway light automations to reduce conflicts etc.

- .pre-commit-config.yaml
- f0b771d | Pin PCH to Python 3.11
> Pin PCH to Python 3.11

- .github/workflows/validate_home_assistant_config.yml
- .gitmodules
- entities/command_line/sensor/current_appdaemon_branch.yaml
- entities/command_line/sensor/current_appdaemon_ref.yaml
- integrations/folder_watcher.yaml
- resources/shell_command/git/get_latest_release.sh
- ceba5a4 | Remove AppDaemon submodule
- 4a9bedb | Update AppDaemon directory paths
- 0e0d0e8 | GHA fix
> Remove AppDaemon submodule

- configuration.yaml
- a3ad744 | Add Add-on folder to external allowlist
> Add Add-on folder to external allowlist

- entities/script/cosmo/cosmo_get_room_id_or_name.yaml
- 6302cec | Fix room name/ID lookup script
- eb3c80b | More fixes
- 9155c18 | Better logging
> Fix room name/ID lookup script

- entities/template/binary_sensor/office_desk_occupied.yaml
- 12a6769 | Update/improve Office Desk Occupation sensor
> Update/improve Office Desk Occupation sensor

- entities/automation/binary_sensor/front_door/open.yaml
- 5d0c2dd | Simplify condition for front door open automation
- 9176441 | Update entities/automation/binary_sensor/front_door/open.yaml
> Simplify condition for front door open automation

- entities/script/notify_will.yaml
- 8c377fa | Add personal/work MacBooks to `script.notify_will`
> Add personal/work MacBooks to `script.notify_will`

- entities/template/sensor/entity_counts/count_low_batteries.yaml
- entities/template/sensor/entity_counts/count_stale_entities.yaml
- entities/template/sensor/entity_counts/count_unavailable_entities.yaml
- 726bcc3 | Add defaults for template sensor attributes
> Add defaults for template sensor attributes

- entities/automation/switch/christmas_tree/turn_on.yaml
- e547ab1 | Add Christmas Tree turn on when someone arrives at home
- bcde3cf | Add condition to check switch exists
> Add Christmas Tree turn on when someone arrives at home

- entities/automation/input_select/target_git_branch/option_selected.yaml
- entities/automation/input_select/target_git_branch/set_options.yaml
- entities/script/input_select/target_git_branch/target_git_branch_set_options.yaml
- 650c7ed | Fix target git branch script responses
- 33257d7 | Ensure no quick repeats from simultaneous branch/ref updates
- 7f41fb4 | Fix bad `if` -.-
- e2684b0 | Invert response check
- 3efbaf1 | Invert again..?
> Fix target git branch script responses

- entities/script/system/script_response_debugger.yaml
- 782cf61 | Add script response debugger
> Add script response debugger

- entities/script/cosmo/cosmo_clean_room.yaml
- Fix bad defaults in script
- Fix bad defaults in script
- Fix bad defaults in script
> Fix bad defaults in script

- entities/sensor/time_date.yaml
- 4363412 | Add `time_date` integration
- 184f730 | Update entities/sensor/time_date.yaml
> Add `time_date` integration

- entities/script/cosmo/cosmo_clean_room.yaml
- b01c9ab | Add door-open timeout to Cosmo's cleaning
> Add door-open timeout to Cosmo's cleaning

- entities/script/cosmo/cosmo_clean_room.yaml
- 873d3c5 | Update Cosmo door wait to 2 hours
> Update Cosmo door wait to 2 hours

- entities/shell_command/ls.yaml
- 43eb421 | Add `shell_command.ls`
> Add `shell_command.ls`

- entities/automation/input_select/cosmo_picture/set_options.yaml
- entities/input_select/cosmo_entity_picture.yaml
- entities/template/sensor/person/person_cosmo.yaml
- 59766ab | Add template sensor for Cosmo on front end
> Add template sensor for Cosmo on front end

- integrations/folder_watcher.yaml
- b66e4e7 | Add UI Lovelace files to folder watcher
> Add UI Lovelace files to folder watcher

- lovelace/dashboards/ui_only/lovelace.dashboard_sandbox.json
- lovelace/dashboards/ui_only/lovelace.home_will.json
- lovelace/dashboards/ui_only/lovelace_dashboards.json
- 17f4507 | Create `lovelace/dashboards/ui_only/lovelace.home_will.json`
- d92f5a1 | Create `lovelace/dashboards/ui_only/lovelace.dashboard_sandbox.json`
- d6765cb | Create `lovelace/dashboards/ui_only/lovelace_dashboards.json`
- 13e6072 | Update `lovelace/dashboards/ui_only/lovelace.home_will.json`
- 344a51d | Update `lovelace/dashboards/ui_only/lovelace.home_will.json`
- 7e5d501 | Update `lovelace/dashboards/ui_only/lovelace.home_will.json`
- 8f15f16 | Update `lovelace/dashboards/ui_only/lovelace.home_will.json`
> Update UI Lovelace Dashboard Files

- .pre-commit-config.yaml
- config_validator.json
- entities/mqtt/sensor/clmtpi/active_git_ref.yaml
- entities/mqtt/sensor/clmtpi/boot_time.yaml
- entities/mqtt/sensor/clmtpi/local_git_ref.yaml
- entities/mqtt/sensor/clmtpi/uptime.yaml
- entities/mqtt/sensor/crtpi/active_git_ref.yaml
- entities/mqtt/sensor/crtpi/boot_time.yaml
- entities/mqtt/sensor/crtpi/local_git_ref.yaml
- entities/mqtt/sensor/crtpi/uptime.yaml
- entities/mqtt/sensor/growpi/active_git_ref.yaml
- entities/mqtt/sensor/growpi/boot_time.yaml
- entities/mqtt/sensor/growpi/local_git_ref.yaml
- entities/mqtt/sensor/growpi/uptime.yaml
- entities/mqtt/sensor/mtrxpi/active_git_ref.yaml
- entities/mqtt/sensor/mtrxpi/boot_time.yaml
- entities/mqtt/sensor/mtrxpi/local_git_ref.yaml
- entities/mqtt/sensor/mtrxpi/uptime.yaml
- entities/mqtt/sensor/octopi/active_git_ref.yaml
- entities/mqtt/sensor/octopi/boot_time.yaml
- entities/mqtt/sensor/octopi/local_git_ref.yaml
- entities/mqtt/sensor/octopi/uptime.yaml
- entities/mqtt/sensor/rtropi/active_git_ref.yaml
- entities/mqtt/sensor/rtropi/boot_time.yaml
- entities/mqtt/sensor/rtropi/local_git_ref.yaml
- entities/mqtt/sensor/rtropi/uptime.yaml
- entities/mqtt/sensor/vsmppi/active_git_ref.yaml
- entities/mqtt/sensor/vsmppi/boot_time.yaml
- entities/mqtt/sensor/vsmppi/local_git_ref.yaml
- entities/mqtt/sensor/vsmppi/uptime.yaml
- ee1125a | Add boot/uptime MQTT sensors
- 939baa6 | Fix units
- 31052aa | Add git ref sensors
> Enhance Pi Stats sensors

- entities/template/binary_sensor/raspberry_pi_online/clmtpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/crtpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/growpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/mtrxpi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/octopi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/rtropi_online.yaml
- entities/template/binary_sensor/raspberry_pi_online/vsmppi_online.yaml
- 7459319 | Add `binary_sensor.octopi_online`
- 773ffbd | Refactor existing pi-online sensors
> Add `binary_sensor.octopi_online`

- entities/automation/binary_sensor/quiet_hours/on.yaml
- entities/template/binary_sensor/quiet_hours.yaml
- 7177d73 | Add script to check for missed Cosmo cleans
- 81bb51b | Fix datetime bugs
- 6e80b72 | Fix missed variable name change
- d2e7db0 | Optimise and add `input_datetime.set_datetime` service call
- 90530be | Housekeeping
- 6afd5d9 | Remove bad filter
> Add script to check for missed Cosmo cleans

- entities/automation/input_select/target_git_branch/option_selected.yaml
- entities/script/debug_persistent_notification.yaml
- entities/script/input_select/target_git_branch/target_git_branch_set_options.yaml
- entities/script/notify_vic.yaml
- entities/script/notify_will.yaml
- 0fa11ed | Fix various minor script bugs
> Fix various minor script bugs

- entities/automation/input_select/target_git_branch/set_options.yaml
- entities/script/input_select/target_git_branch/target_git_branch_set_options.yaml
- 6aeb008 | Fix incorrect automatic branch changing
- f724c92 | Remove unnecessary delay
> Fix incorrect automatic branch changing

- entities/automation/binary_sensor/quiet_hours/on.yaml
- entities/automation/cover/bedroom_blinds/register_stop_state.yaml
- entities/automation/cover/lounge_blinds/register_stop_state.yaml
- entities/automation/cover/office_blinds/register_stop_state.yaml
- entities/automation/cover/office_desk/work_mode.yaml
- entities/automation/crt_pi/crt_power_state_from_crt_pi.yaml
- entities/automation/homeassistant/load_gh_cli_on_start.yaml
- entities/automation/input_select/cosmo_entity_picture/set_options.yaml
- entities/automation/webhook/git_branch_or_tag_deleted.yaml
- entities/automation/webhook/update_pull_request_sensor.yaml
- entities/script/crt_pi_update_display.yaml
- entities/script/office_desk_sitting_mode.yaml
- entities/script/office_desk_standing_mode.yaml
- 33368bb | Fix variable passing with `script.turn_on` calls
> Fix variable passing with `script.turn_on` calls

- entities/script/turn_off_physical_room.yaml
- 4c929bc | Fix more script default values
> Fix more script default values

- entities/script/cosmo/cosmo_send_clean_requests.yaml
- 98d2246 | Only send Cosmo notifications if close to home
- c0a46fc | Minor updates
> Only send Cosmo notifications if close to home

- entities/automation/input_number/prusa_i3_mk3/bed_target/set.yaml
- entities/automation/input_number/prusa_i3_mk3/tool_0_target/set.yaml
- entities/automation/sensor/octoprint_bed_target/set.yaml
- entities/automation/sensor/octoprint_tool_0_target/set.yaml
- entities/input_number/prusa_i3_mk3/prusa_i3_mk3_target_bed_temperature.yaml
- entities/input_number/prusa_i3_mk3/prusa_i3_mk3_target_hotend_temperature.yaml
- 36ad9a4 | Add Prusa i3 MK£ temperature controls
- df23dee | Add defaults for state-int conversion
- 948a6cf | Add check for unavailable states
- ae2e1ab | Fix MQTT payload
- 9259911 | Add wait to MQTT automations
- e140911 | Add more checks for unavailable states
- a002db7 | Add more checks for unavailable states
> Add Prusa i3 MK3 temperature controls

- entities/automation/person/will/home.yaml
- entities/automation/person/will/leaving_work.yaml
- 0f19bcc | Fix automation conditions
> Fix automation conditions

- entities/automation/webhook/git_branch_or_tag_created.yaml
- 0af486c | Update notif content
- e94dc18 | Fix content
> Update notif content

- .github/workflows/validate_home_assistant_config.yml
- 35d241e | Change to forked Config Check GHA
- caffab2 | Actually use new feature
- d1c4462 | Update ref
- 1a09682 | Update ref
- 1d40e3f | Add ignore pattern
- 2c9996b | Fix key
- e19a7be | Update ref/fix pattern
- 2520ac1 | Update ref
- fb2af94 | 24773048b6bffd1e494655400f6978304e12deeb
- c4fab40 | 656e26c2ef187ba57453d7248e6bc1f76b819ae6
- 5fb2733 | Test different pattern
- 1577402 | 64559ab6620631813d1437dfc18270ccb28b1b15
- 1941fbf | Update to `main` reference
> Change to forked Config Check GHA

- entities/script/functions/log_exception.yaml
- entities/script/functions/throw_exception.yaml
- d1d1fb9 | Add script for throwing exceptions
- 14eaa51 | Fix typo
- a46ee79 | Change to just logging instead of throwing
- 81b61ac | Fix URL issue
> Add script for logging exceptions

- entities/automation/binary_sensor/front_door/open.yaml
- entities/automation/binary_sensor/hallway_motion_sensor/on.yaml
- entities/automation/cosmo/nightly_kitchen_clean.yaml
- entities/automation/crt_pi/update_display.yaml
- entities/automation/hue_remote/office/button_4/long_press.yaml
- entities/automation/input_boolean/bedroom_entity_header/auto_turn_off.yaml
- entities/automation/input_boolean/bedroom_entity_header/auto_turn_on.yaml
- entities/automation/input_boolean/lounge_entity_header/auto_turn_off.yaml
- entities/automation/input_boolean/lounge_entity_header/auto_turn_on.yaml
- entities/automation/input_boolean/office_entity_header/auto_turn_off.yaml
- entities/automation/input_boolean/office_entity_header/auto_turn_on.yaml
- entities/automation/mtrxpi/update_display.yaml
- entities/automation/octopi/fan_control.yaml
- entities/automation/switch/christmas_tree/turn_on.yaml
- entities/script/cosmo/cosmo_tag_scanned.yaml
- entities/script/office_desk_set_position.yaml
- entities/script/turn_off_physical_room.yaml
- entities/template/binary_sensor/bank_holiday.yaml
- entities/template/binary_sensor/hifi_system_is_volume_muted.yaml
- entities/template/binary_sensor/office_desk_occupied.yaml
- entities/template/binary_sensor/office_desk_standing_and_occupied.yaml
- entities/template/sensor/distance/vic_and_will_distance.yaml
- entities/template/sensor/distance/vic_distance_from_home.yaml
- entities/template/sensor/distance/will_distance_from_home.yaml
- entities/template/sensor/floorplan_icons/clmtpi_floorplan_icon.yaml
- entities/template/sensor/hifi_system_media_metadata.yaml
- lovelace/decluttering_templates.yaml
- pyproject.toml
https://www.home-assistant.io/docs/configuration/templating/#home-assistant-template-extensions
- dd28700 | Refactor Jinja templates to use Home Assistant template extensions
- cc39523 | Fix bad entity IDs
> Refactor Jinja templates to use Home Assistant template extensions

- entities/script/functions/run_dynamic_script.yaml
- 1edef29 | Add dynamic script runner
- 87312ca | Fix indentation
- c623e45 | Fix example
> Add dynamic script runner

- entities/automation/input_select/cosmo_entity_picture/set_options.yaml
- 70c81a6 | Fix debug notification content
> Fix debug notification content

- entities/script/functions/run_dynamic_script.yaml
- c0c58e8 | Allow suppressing dynamic script notifications
> Allow suppressing dynamic script notifications

- entities/switch/prusa_i3_mk3_power.yaml
- 1cd2750 | Allow for multiple Prusa "offline" states
> Allow for multiple Prusa "offline" states

- .pre-commit-config.yaml
- entities/switch/prusa_i3_mk3_power.yaml
- 036d98a | Remove invalid step in `switch.prusa_i3_mk3_power.turn_on`
- 09b07c8 | Apply suggestions from code review
> Remove invalid step in `switch.prusa_i3_mk3_power.turn_on`

- entities/automation/remote/kitchen.yaml
- integrations/README.md
- c59d7d0 | Add automation for Kitchen Spotlight control
- d71c629 | Queue button pushes and increase transition to 1s
- d77a476 | Explicitly use entity IDs
> Add automation for Kitchen Spotlight control

- config_validator.yml
- integrations/README.md
- 5255ffc | Add variables to automations and scripts in README
- 55848da | [pre-commit.ci] auto fixes from pre-commit.com hooks
> Add variables to automations and scripts in README

- entities/automation/remote/kitchen.yaml
- integrations/README.md
- 3549909 | Toggl kitchen light mode at night
> Toggle kitchen light mode at night

- entities/template/sensor/time_of_day.yaml
- integrations/README.md
- ead7886 | Add `sensor.time_of_day`
- 7108a74 | Add icon
> Add `sensor.time_of_day`

- .pre-commit-config.yaml
- integrations/README.md
https://github.com/worgarside/home-assistant-config-validator/releases/tag/4.0.0
> Bump `home-assistant-config-validator` to 4.0.0

- entities/automation/switch/mtrxpi_power/off.yaml
- entities/automation/switch/mtrxpi_power/on.yaml
- entities/switch/mtrxpi_power.yaml
- integrations/README.md
- 7cb8d2d | Add combo switch for MtrxPi (Pi+Matrix)
- 13a4942 | Add safety automations
> Add combo switch for MtrxPi (Pi+Matrix)

- entities/switch/mtrxpi_power.yaml
- 564fb84 | Fix inverted icon for `switch.mtrxpi_power`
> Fix inverted icon for `switch.mtrxpi_power`

- entities/script/mtrxpi/mtrxpi_queue_content.yaml
- 7f67f01 | Add de-duping notification ID to MtrxPi debug notifs
> Add de-duping notification ID to MtrxPi debug notifs

- entities/sensor/tomorrow_io_realtime_weather.yaml
- dca159a | Fix bad template weather sensor default
> Fix bad template weather sensor default

- entities/input_text/appdaemon/monzo_auth_token_auto_saver.yaml
- entities/input_text/appdaemon/truelayer_auth_token_amex.yaml
- entities/input_text/appdaemon/truelayer_auth_token_amex_auto_saver.yaml
- entities/input_text/appdaemon/truelayer_auth_token_hsbc.yaml
- entities/input_text/appdaemon/truelayer_auth_token_monzo.yaml
- entities/input_text/appdaemon/truelayer_auth_token_santander.yaml
- entities/input_text/appdaemon/truelayer_auth_token_starling.yaml
- entities/input_text/appdaemon/truelayer_auth_token_starling_joint.yaml
- integrations/README.md
- 7d4d38a | Add input text for Amex auto saver code
- 5953e49 | Add Monzo auto saver auth token
- 81ce3b3 | Update max length/mode
> Add input text for Amex auto saver code

- entities/automation/cube/knock.yaml
- entities/automation/cube/rotate.yaml
- entities/automation/cube/slide.yaml
- entities/input_text/cube/cube_entity_1.yaml
- entities/input_text/cube/cube_entity_2.yaml
- entities/input_text/cube/cube_entity_3.yaml
- entities/input_text/cube/cube_entity_4.yaml
- entities/input_text/cube/cube_entity_5.yaml
- entities/input_text/cube/cube_entity_6.yaml
- entities/template_triggered/sensor/cube_active_face.yaml
- entities/template_triggered/sensor/cube_latest_event.yaml
- integrations/README.md
- 54b39cd | Add template sensor for Cube active face
- 509d0ab | Add `time_fired` attribute
- 7cae8c7 | Add commands/attributes
- ef9e2fc | Fix multiple command triggers
- d0e9114 | Add inputs to set controlled entities
- 0d0e8c7 | Add cube rotation automation
- 18caba1 | Fix test notification
- a1c8e34 | Another notif fix
- 67e8a40 | Fix field name
- 12a0f4a | :(
- e0c961e | Update rotation automation
- 99b6df3 | Add sensor for latest event
- 7d83675 | Add Cube knock automation
- 6382640 | Fix default syntax
- 2e3ed4b | Add Cube Slid automation
- 6a62867 | [pre-commit.ci] auto fixes from pre-commit.com hooks
- 52e7732 | Fix cover position calculation
- a3d5946 | [pre-commit.ci] auto fixes from pre-commit.com hooks
> Add Aqara Cube automations

- entities/script/cosmo/cosmo_clean_room.yaml
- integrations/README.md
- 263054a | Set Cosmo suction level before cleaning room
> Set Cosmo suction level before cleaning room

- entities/automation/cosmo/nightly_kitchen_clean.yaml
- 93e23e3 | Wait for lounge/kitchen lights out + 10 mins for Cosmo nightly clean
> Wait for lounge/kitchen lights out + 10 mins for Cosmo nightly clean

- .gitignore
- entities/script/notify_vic.yaml
- entities/script/notify_will.yaml
- entities/script/shell_command/gh_cli/gh_issue_create.yaml
- integrations/README.md
- c89219b | Add `script.gh_issue_create`
- aff57b7 | Unrelated script argument updates
- 0c05910 | Add input names and fix arguments
- 39f9702 | Update inputs for usability
- ac05eb5 | Add response variable
- fdde5ce | Make body required
- dd4cf77 | Fix formatting/response
- adacbbe | Formatting and bug fix
- d0d04ce | More formatting fixes
- ca83c06 | Final(?) formatting fix
- 007f82a | ;_;
- 4728648 | Update script to use body file argument
- 79ff6dc | Ignore all GitHub token files
- 46d6e67 | Add notification for issue output
- d227d9e | Fix step order -.-
> Add `script.gh_issue_create`

- entities/automation/media_player/topaz_sr10/timeout.yaml
Closes #799
---
- 0d58463 | Turn off amp when MacBook disconnects from FiiO E10
> Turn off amp when MacBook disconnects from FiiO E10

- entities/script/shell_command/gh_cli/gh_issue_create.yaml
- entities/shell_command/file_operations/write_file.yaml
Resolves #925
---
- 683f830 | Add better escaping to `shell_command.write_file`
- 59394b7 | Add logging to `script.gh_issue_create`
- 4c2c201 | Update error logs
> Add better escaping to `shell_command.write_file`

- entities/automation/cosmo/nightly_kitchen_clean.yaml
Closes #923
---
- f712ea5 | Disable carpet boost for nightly clean
- 6625d2b | Update conditions
> Disable carpet boost for nightly clean

- lovelace/decluttering_templates.yaml
---
- 0c6a3bb | Fix syntax error in decluttering template
> Fix syntax error in decluttering template

- entities/command_line/sensor/current_gh_cli_user.yaml
- integrations/README.md
---
- b0f38c1 | Add `sensor.current_gh_cli_user`
> Add `sensor.current_gh_cli_user`

- entities/automation/gh_cli/user_updated.yaml
- entities/automation/input_select/gh_cli_active_user/option_selected.yaml
- entities/input_select/gh_cli_active_user.yaml
- integrations/README.md
---
- c0cab5f | Add controls to select active GH CLI user
- 90c115d | Add automation to sync input select
- 06a0c26 | Fix bad script call
- 9499d3d | Add step to revert bad user change
- d541eda | Add more detail to error notification
> Add controls to select active GH CLI user

- entities/shell_command/file_operations/read_file.yaml
- entities/shell_command/file_operations/write_file.yaml
---
- 177d069 | Update file read/write shell commands to use base64
> Update file read/write shell commands to use base64

- entities/script/shell_command/gh_cli/gh_issue_create.yaml
---
- 8f096ca | Update `script.gh_issue_create` for base64 file handling
> Update `script.gh_issue_create` for base64 file handling

- entities/automation/event/repair/state_change.yaml
- entities/template/sensor/nature/time_of_day.yaml
- integrations/README.md
---
- 48810ca | Automate repair logging as GitHub issue
- 7bf99f2 | [pre-commit.ci] auto fixes from pre-commit.com hooks
- 952bbcb | Run PCHs
- b4681c4 | Unrelated fix
> Automate repair logging as GitHub issue

- entities/automation/event/repair/state_change.yaml
---
- e85dc21 | Remove test value from GH CLI `gh issue list`
- ef18f49 | Fix command
> Remove test value from GH CLI `gh issue list`

- entities/automation/event/repair/state_change.yaml
---
- a2c08d0 | Only close GitHub issues from `main` branch
> Only close GitHub issues from `main` branch

- entities/automation/switch/air_freshener/timeout.yaml
- entities/input_number/air_freshener_timeout.yaml
- integrations/README.md
---
- 143db15 | Add configurable automation for air freshener timeout
> Add configurable automation for air freshener timeout

- entities/automation/event/repair/state_change.yaml
---
- d876f98 | Fix bug in issue body formatting
> Fix bug in issue body formatting

- integrations/media_extractor.yaml
---
- 50a48f1 | Remove `media_extractor` YAML configuration
> Remove `media_extractor` YAML configuration

- .pre-commit-config.yaml
- entities/automation/person/will/home.yaml
- entities/automation/remote/kitchen.yaml
- entities/automation/remote/lounge.yaml
---
- 9c61e50 | Update HACV to 4.2.0
> Update HACV to 4.2.0

- entities/script/cosmo/cosmo_send_clean_requests.yaml
---
- cce99c9 | Temporarily block Cosmo clean requests from going to Vic
> Temporarily block Cosmo clean requests from going to Vic

- entities/automation/person/will/leaving_work.yaml
---
- d09e0ef | Bugfixes for "Will leaving work" notification
> Bugfixes for "Will leaving work" notification

- entities/script/notify_will.yaml
---
- c083631 | Disable work MBP notifications temporarily
> Disable work MBP notifications temporarily

- entities/automation/fan/prusa_i3_enclosure_fan/turn_off.yaml
- entities/automation/fan/prusa_i3_enclosure_fan/turn_on.yaml
- integrations/README.md
---
- 1f81ee7 | Add control automations for enclosure fan
> Add control automations for enclosure fan

- entities/automation/hue_remote/bedroom/button_1/long_press.yaml
- entities/automation/hue_remote/bedroom/button_1/press.yaml
- entities/automation/hue_remote/bedroom/button_4/long_press.yaml
- entities/automation/hue_remote/bedroom/button_4/press.yaml
- integrations/README.md
Closes #935
---
- a921629 | Add bedroom Hue remote automations
> Add bedroom Hue remote automations

- entities/automation/cover/bedroom_blinds/close_after_sunset.yaml
- integrations/README.md
---
- 175ee6d | Turn Moomin box on when bedroom blinds close
- 6d6bbbc | Only turn on if somebody home
> Turn Moomin box on when bedroom blinds close

- entities/mqtt/sensor/flmtpi/ambient_humidity.yaml
- entities/mqtt/sensor/flmtpi/ambient_temperature.yaml
---
- 49e40f4 | Stop recording invalid FlmtPi temp/rhum values
> Stop recording invalid FlmtPi temp/rhum values

- entities/script/cosmo/cosmo_clean_room.yaml
- integrations/README.md
---
- 9cbd232 | Add "real"(?) defaults for `script. cosmo_clean_room`
> Add "real"(?) defaults for `script.cosmo_clean_room`

- entities/automation/hue_remote/bedroom/button_1/long_press.yaml
---
- 5a3bd81 | Fix invalid automation YAML
> Fix invalid automation YAML

- entities/mqtt/sensor/crtpi/local_ip_address.yaml
- entities/mqtt/sensor/growpi/local_ip_address.yaml
- entities/mqtt/sensor/mtrxpi/local_ip_address.yaml
- entities/mqtt/sensor/octopi/local_ip_address.yaml
- entities/mqtt/sensor/rtropi/local_ip_address.yaml
- entities/mqtt/sensor/vsmppi/local_ip_address.yaml
---
- 3702ed0 | Add defaults for local Pi IPs
> Add defaults for local Pi IPs

- entities/script/input_select/target_git_branch/target_git_branch_set_options.yaml
---
- d85f77c | Fix bad Git branch behaviour
> Fix bad Git branch behaviour

- entities/mqtt/sensor/crtpi/ambient_humidity.yaml
- entities/mqtt/sensor/crtpi/ambient_temperature.yaml
- entities/mqtt/sensor/octopi/ambient_humidity.yaml
- entities/mqtt/sensor/octopi/ambient_temperature.yaml
---
- 2633012 | Add JSON attributes to DHT22 sensors
> Add JSON attributes to DHT22 sensors

- integrations/recorder.yaml
---
- 84f1828 | Stop ignoring voltage entities in recorder
> Stop ignoring voltage entities in recorder

- entities/automation/crtpi/update_display.yaml
- entities/automation/mtrxpi/content_trigger/now_playing.yaml
- entities/input_select/mtrxpi/mtrxpi_media_player_source.yaml
- integrations/README.md
---
- d9d390b | Align now playing automation implementations
> Align now playing automation implementations

- entities/template/sensor/soil_saturation/soil_saturation_1.yaml
- entities/template/sensor/soil_saturation/soil_saturation_2.yaml
---
- d290a07 | Fix saturation sensors defaulting to 100% when no reading
> Fix saturation sensors defaulting to 100% when no reading available

- entities/template/sensor/soil_saturation/soil_saturation_2.yaml
---
- c8629cc | Fix bad template in saturation 2
> Fix bad template in saturation 2

- integrations/recorder.yaml
---
- 175652b | Stop recording datetime sensors
> Stop recording datetime sensors

- integrations/logger.yaml
---
- 380f439 | Filter Denon logs
> Filter Denon logs

- integrations/recorder.yaml
---
- 7d81a68 | Record database size
> Record database size

- entities/automation/binary_sensor/quiet_hours/on.yaml
- entities/automation/cover/office_desk/work_mode.yaml
- entities/automation/crtpi/cpu_fan_control.yaml
- entities/automation/input_datetime/cosmo/next_clean_due/set.yaml
- entities/automation/mtrxpi/content_trigger/raining_grid.yaml
- entities/automation/octopi/cpu_fan_control.yaml
- entities/cover/office/office_desk.yaml
- entities/script/office_desk_set_position.yaml
- entities/script/office_desk_stop_moving.yaml
- entities/switch/prusa_i3_mk3_power.yaml
- entities/template/binary_sensor/office_desk_standing_mode.yaml
- entities/template/image/prusa_i3_thumbnail.yaml
- entities/template/sensor/entity_counts/low_batteries.yaml
- entities/template_triggered/sensor/topaz_sr10_active_child.yaml
- integrations/README.md
---
- 3e973bb | Add defaults for int coercion in Jinja templates
- 01aadcd | More defaults
> Add defaults for int coercion in Jinja templates

- entities/mqtt/sensor/mtrxpi/content_queue.yaml
---
- f8f877e | Add template parser to content queue attrs
- 21a6118 | Fix parser
> Add template parser to content queue attrs

- entities/automation/cosmo/nightly_kitchen_clean.yaml
- entities/automation/remote/coffee_table/single_press.yaml
- entities/mqtt/switch/prusa_i3/enclosure_fan.yaml
- entities/script/cosmo/cosmo_send_clean_requests.yaml
- entities/script/functions/run_dynamic_script.yaml
- entities/script/notify_vic.yaml
- entities/script/notify_will.yaml
- entities/script/office_desk_sitting_mode.yaml
- entities/script/office_desk_standing_mode.yaml
- entities/shell_command/mark_pr_as_ready_for_review.yaml
- entities/template/image/prusa_i3_thumbnail.yaml
- integrations/README.md
---
- 80652b7 | Ensure all `| bool` usages in Jinja templates have valid defaults
> Ensure all `| bool` usages in Jinja templates have valid defaults

- integrations/recorder.yaml
---
- 4050975 | Reduce recorder data volume
> Reduce recorder data volume

- entities/automation/mtrxpi/content_trigger/clock.yaml
- integrations/README.md
---
- 5e5f285 | Add content trigger for MtrxPi clock
> Add content trigger for MtrxPi clock

- config_validator.yml
- entities/light/mtrxpi_led_matrix.yaml
- entities/light/mtrxpi_led_matrix_brightness.yaml
- integrations/README.md
- integrations/light.yaml
---
- 47918e9 | Add template light for MtrxPi
- 56ee91d | Fix incorrect key usage
- 70df619 | Update turn_on action call
- 2e6f5dd | Convert abs brightness value to %age
- 116e9a4 | Fix bad calc
- ec499c0 | Fix level template
- cd8c1e2 | Update light name
> Add template light for MtrxPi

- entities/automation/presence/office/beanbag.yaml
---
- afdacbd | Fix `brightness` key
> Fix `brightness` key

- entities/template/binary_sensor/office_desk_occupied.yaml
---
- b140f55 | Fix logic for occupation sensor
> Fix logic for occupation sensor

- entities/mqtt/number/mtrxpi/raining_grid/distance_between_plants.yaml
- entities/mqtt/number/mtrxpi/raining_grid/leaf_growth_chance.yaml
- entities/mqtt/number/mtrxpi/raining_grid/plant_death_propagation_speed.yaml
- entities/mqtt/number/mtrxpi/raining_grid/plant_growth_chance.yaml
- entities/mqtt/number/mtrxpi/raining_grid/plant_limit.yaml
- integrations/README.md
---
- 76c676e | Add MQTT entities for MtrxPi plants
> Add MQTT entities for MtrxPi plants

- integrations/logger.yaml
---
- 1e40bc8 | Update `logger` filters
> Update `logger` filters

- entities/script/notify_will.yaml
- entities/template/binary_sensor/office_desk_occupied.yaml
- entities/template/binary_sensor/st_macbook_pro_docked.yaml
- entities/template/binary_sensor/work_macbook_pro_docked.yaml
- entities/template_triggered/sensor/topaz_sr10_active_child.yaml
- integrations/README.md
---
- f4d251f | Update references to work MBP
> Update references to work MBP

- entities/automation/light/desk_lamp/turn_on.yaml
---
- 62820ec | Auto-turn desk lamp off too
- 6caa5ae | Add time check before turning off
> Auto-turn desk lamp off too

- .gitignore
- entities/automation/binary_sensor/will_s_desk_occupancy/state_change.yaml
- entities/automation/fan/desk_fan/state_change.yaml
- entities/automation/light/desk_lamp/state_change.yaml
- entities/automation/light/desk_lamp/turn_on.yaml
- entities/automation/light/office_shapes/state_change.yaml
- entities/automation/var/will_s_desk_state_manager/attribute_timeout.yaml
- entities/input_boolean/sync_will_s_desk_state_manager.yaml
- entities/var/will_s_desk_state_manager.yaml
- integrations/README.md
---
- a2d51d1 | Add state manager var for Will's desk
- 0f87e98 | Fix invalid entity name
- 092ec2c | Automate Will's desk entities based on occupancy
- 5f48701 | Update automation blocker
- 0948c77 | Update state manager handling
- afb16c1 | Fix service calls
- 7520a34 | Parallelise entity control
- 45a0772 | Fix variable scope issues
- e568c20 | Fix variables
- f034fc5 | Add timeout automation
- 5b7bbd7 | Refactor whitespace
> Add state manager var for Will's desk

- entities/automation/hue_remote/bedroom/button_1/press.yaml
- entities/automation/hue_remote/bedroom/button_2/long_press.yaml
- entities/automation/hue_remote/bedroom/button_2/press.yaml
- entities/automation/hue_remote/bedroom/button_3/long_press.yaml
- entities/automation/hue_remote/bedroom/button_3/press.yaml
- integrations/README.md
---
- ccf8b01 | Update bedroom Hue remote functionality
> Update bedroom Hue remote functionality

- entities/automation/binary_sensor/office_presence_sensor/state_change.yaml
- integrations/README.md
---
- d703df8 | Update occupancy to be Office-based, not desk-based
> Update occupancy to be Office-based, not desk-based

- entities/automation/cover/office_desk/work_mode.yaml
---
- dd4af34 | Update work mode automation conditions
> Update work mode automation conditions

- entities/automation/remote/lounge_desk/hold.yaml
- integrations/README.md
---
- b45c161 | Automate Vic's desk fan
> Automate Vic's desk fan

- entities/command_line/sensor/addons/castsponsorskip_status.yaml
- entities/template/sensor/addon_stats/castsponsorskip_cpu_usage.yaml
- entities/template/sensor/addon_stats/castsponsorskip_memory_usage.yaml
- integrations/README.md
- secrets.fake.yaml
---
- 93752aa | Add sensors for CastSponsorSkip stats
> Add sensors for CastSponsorSkip stats

- entities/automation/cover/office_desk/work_mode.yaml
---
- 3939ea4 | Only use work mode automation when desk is occupied
> Only use work mode automation when desk is occupied

- entities/automation/binary_sensor/lounge_diffuser_needs_water/off.yaml
- integrations/README.md
---
- fa918f4 | Fix "diffuser needs water" alert
> Fix "diffuser needs water" alert

- dev_tools/color_generator.py
- entities/command_line/sensor/addons/nextcloud_status.yaml
- entities/template/sensor/addon_stats/nextcloud_cpu_usage.yaml
- entities/template/sensor/addon_stats/nextcloud_memory_usage.yaml
- integrations/README.md
- secrets.fake.yaml
---
- 18e5a1d | Add Nextcloud addon sensors
- adabd7e | Update color gen script
- 37853a7 | Update color gen script
> Add Nextcloud addon sensors

- entities/template/sensor/nature/time_of_day.yaml
---
- 0606b4d | Add lower limit to `time_of_day` being "night"
> Add lower limit to `time_of_day` being "night"

- entities/script/notify_will.yaml
---
- 781c863 | Update device name for Pixel 6 Pro
- 1b08bc5 | Fix error
> Update device name for Pixel 6 Pro

- dev_tools/color_generator.py
- entities/command_line/sensor/addons/nginx_proxy_manager_status.yaml
- entities/template/sensor/addon_stats/nginx_proxy_manager_cpu_usage.yaml
- entities/template/sensor/addon_stats/nginx_proxy_manager_memory_usage.yaml
- integrations/README.md
- secrets.fake.yaml
---
- b45004d | Add NGINX Proxy Manager sensors
> Add NGINX Proxy Manager sensors

- entities/script/notify_will.yaml
---
- 442f72a | Fix notification service
> Fix notification service

- entities/sensor/plex_recently_added.yaml
- integrations/README.md
- secrets.fake.yaml
---
- 533e6a3 | Add `sensor.plex_recently_added`
> Add `sensor.plex_recently_added`

- entities/script/ir_blaster/topaz_sr10/ir_blaster_topaz_sr10_issue_command.yaml
---
- 344a826 | Fix script for amp IR blaster
> Fix script for amp IR blaster

- .gitignore
- .pre-commit-config.yaml
- entities/automation/light/moomin_box/on.yaml
- integrations/README.md
---
- 80b59ef | Add workaround automation for Moomin box light
> Add workaround automation for Moomin box light

- .gitignore
- entities/mqtt/sensor/zigbee2mqtt/network_map.yaml
- integrations/README.md
---
- 2ce3f2a | Add sensor for Z2M network map card
> Add sensor for Z2M network map card

- entities/automation/fan/air_purifier/control.yaml
- integrations/README.md
---
- bf09f2c | Add air purifier control automation
- 000d21f | Simplify conditions
- 015a0b0 | Update entities/automation/fan/air_purifier/control.yaml
- 3b85029 | [pre-commit.ci] auto fixes from pre-commit.com hooks
> Add air purifier control automation

- entities/automation/input_boolean/air_purifier_quiet_mode/toggle.yaml
- entities/script/fan/air_purifier/air_purifier_update_fan_speed.yaml
- integrations/README.md
---
- 8bf7424 | Only update Air Purifier fan speed when required
- d1cf425 | Apply condition to whole script
- 3f66e45 | Revert "Apply condition to whole script"
- 5e48acd | Fix Vic meeting condition
> Only update Air Purifier fan speed when required

- entities/automation/homeassistant/integrations/speedtest/reload.yaml
- integrations/README.md
---
- c8b03d0 | Reload Speedtest when integration fails
> Reload Speedtest when integration fails

- integrations/recorder.yaml
- secrets.fake.yaml
---
- 8510ee6 | Update `db_url` secret name
- 2a4ff27 | Update purge TTL to 5 years
- 5b58e2c | Fake secret
> Update `db_url` secret name

- resources/shell_command/gh_cli/get_gh_cli.sh
---
- d2574e1 | Update GH CLI package for new machine
> Update GH CLI package for new machine

- entities/sensor/plex_recently_added.yaml
- secrets.fake.yaml
---
- 5a47054 | Update Plex host
> Update Plex host

- integrations/influxdb.yaml
---
- e4f8fd4 | Fix SSL value for InfluxDB config
> Fix SSL value for InfluxDB config

- entities/script/notify_will.yaml
---
- f5c743a | Fix notify UUID
> Fix notify UUID

- entities/command_line/sensor/pve/companion_cube_cpu_temperature.yaml
- integrations/README.md
---
- a00ada4 | Add CPU temp sensor for Companion Cube
- 297db81 | formatting
- 518e28f | fix ssh issue
> Add CPU temp sensor for Companion Cube

- entities/automation/remote/will_s_desk/button_1/single.yaml
---
- c250252 | Improves office light toggle functionality
> Improves office light toggle functionality

- entities/automation/homeassistant/handle_service_reload.yaml
---
- 83ec558 | Silence reload automation
> Silence reload automation

- .cursor/rules/home-assistant.mdc
- entities/automation/binary_sensor/front_door/open.yaml
- entities/automation/light/upper_landing_lights/timeout.yaml
---
- 38c9dd5 | Update front door automation
> Update front door automation

- entities/automation/binary_sensor/kitchen_presence/off.yaml
- entities/automation/binary_sensor/kitchen_presence/on.yaml
- integrations/README.md
---
- c7ff5ce | Refines Cosmo automation logic
> Refines Cosmo automation logic

- entities/automation/light/wardrobe_lights/auto_off.yaml
- integrations/README.md
---
- 426b74c | Adds auto-off for lights
> Adds auto-off for wardrobe lights

- entities/automation/binary_sensor/basement_presence/on.yaml
---
- f30feec | Fix Cosmo auto-pause condition
> Fix Cosmo auto-pause condition

- entities/automation/notification/prusa_i3/user_input_required.yaml
---
- ea461db | Fix false positive 3d printer notifications
> Fix false positive 3d printer notifications

- entities/automation/light/will_s_office_shapes/reboot_on_unavailable.yaml
- integrations/README.md
---
- 7e263ae | Adds automation to reboot office shapes on unavailable
> Adds automation to reboot office shapes on unavailable

- entities/automation/cosmo/nightly_kitchen_clean.yaml
- entities/automation/fan/kitchen_extractor_vent/control.yaml
---
- e0e3715 | Fix `basement_occupancy` refs
> Fix `basement_occupancy` refs

- entities/automation/binary_sensor/vic_s_office_occupancy/state_change.yaml
- entities/automation/binary_sensor/will_s_office_presence_sensor/state_change.yaml
- entities/automation/fan/desk_fan/state_change.yaml
- entities/automation/light/desk_lamp/state_change.yaml
- entities/automation/light/lower_hallway_lights/on.yaml
- entities/automation/light/lower_hallway_lights/timeout.yaml
- entities/automation/light/office_shapes/state_change.yaml
- entities/automation/var/vic_s_office_state_manager/attribute_timeout.yaml
- entities/automation/var/will_s_desk_state_manager/attribute_timeout.yaml
- entities/automation/var/will_s_office_state_manager/attribute_timeout.yaml
- entities/var/vic_s_office_state_manager.yaml
- entities/var/will_s_office_state_manager.yaml
- integrations/README.md
---
- d24f8a4 | Updates lower hallway occupancy entity ID
- 405dad1 | Update office state manager entity ID
- dfb0944 | Adds mushroom lamp to presence detection
- 7a9e880 | Adds Vic's office state management
> Adds Vic's office state management

- entities/automation/person/will/leaving_work.yaml
---
- 873e77f | Remove old nest hub
> Remove old nest hub

- entities/automation/binary_sensor/vic_s_office_occupancy/on.yaml
- integrations/README.md
---
- abdb9f7 | Turn on Shell Lamp when Vic's office occupied
- f5d6211 | PR suggestion
> Turn on Shell Lamp when Vic's office occupied

- entities/script/turn_off_physical_room.yaml
- integrations/README.md
---
- ddf1126 | Fix turn off script
- 554ea66 | Add debounce
- 61a2946 | Change order
> Fix turn off script

- entities/automation/binary_sensor/lounge_occupancy/on.yaml
---
- 96fa2db | Add time condition to lounge occupancy automation
> Add time condition to lounge occupancy automation

- entities/automation/binary_sensor/will_s_office_presence_sensor/state_change.yaml
---
- 0db7fde | Adds purple color to office LED ring
> Adds purple color to office LED ring

- entities/automation/binary_sensor/basement_presence/on.yaml
- integrations/README.md
---
- c98ead4 | Adjusts kitchen lighting based on time
> Adjusts kitchen lighting based on time

- entities/automation/light/upper_landing_lights/on.yaml
- integrations/README.md
---
- d6bdfcf | Lower limit for upper landing light
> Lower limit for upper landing light

- entities/automation/cover/office_desk/keepalive.yaml
---
- 72705a7 | Updates office desk connect button
> Updates office desk connect button

- entities/automation/notification/rain_door_open_alert.yaml
- entities/script/notify_vic.yaml
- integrations/README.md
---
- dd8a74d | Add alert for roof door open in rain
> Add alert for roof door open in rain

- entities/template_triggered/sensor/apollo/apollo_plt_1b_begonia_last_online.yaml
- entities/template_triggered/sensor/apollo/apollo_plt_1b_coleus_last_online.yaml
- entities/template_triggered/sensor/apollo/apollo_plt_1b_monstera_last_online.yaml
- entities/template_triggered/sensor/apollo/apollo_plt_1b_spider_plant_last_online.yaml
- integrations/README.md
---
- 6de6427 | PLT-1B Last Online Sensors
- 45f5b8c | Handles "unknown" state and provides default timestamp
> PLT-1B Last Online Sensors
